name: Manage Rancher Users
on:
  workflow_dispatch: # run manually
  push:
    paths:
      - "manifests/**" # trigger only when manifests change
jobs:
  manage-users:
    runs-on: self-hosted
    env:
      # Rancher API settings
      RANCHER_URL: "http://rancher.13.208.242.148.sslip.io"
      RANCHER_API_TOKEN: ${{ secrets.RANCHER_API_TOKEN }} # Token for user with Manage Users global role

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: '1.31'

      - name: Apply Rancher user manifests
        run: |
          kubectl apply -f manifests/user.yaml
